### ISSUE TITLE
ManyToOneConcurrentArrayQueueMailboxActorTest does not use correct mailbox

### ISSUE THREAD

**Issue by bwehrle** [vlingo/xoom-actors#100]
The ManyToOneConcurrentArrayQueueMailboxActorTest actually does not instantiate the appropriate mailbox.  There are two problems here:

1. One line of code is missing to enable the mailbox plugin
2. There is no way to check that the right mailbox- or plugin- is being used for the actor except by side-effects

Problem 1 is easy to solve

Problem 2 requires some more introspection to check that the state of the system corresponds to the expected.  I added a simple way to know what type of Mailbox that an actor is using.  This is very limited.  Ideally:

* Registrar could present an immutable view of registered plugins
* Actor would have reference to such a view to know what plugins were applied to it (eg: mailbox)

See my PR to address issue 1 and partially address issue 2.

**Comment by VaughnVernon** [comment]
@bwehrle From the above only 2 is fixed. Would you please submit a new PR for 1?

From @pflueras Slack message:

```
#100 is not fixed entirely because of
1. One line of code is missing to enable the mailbox plugin
Most likely Brian will submit a new PR..
```

**Comment by bwehrle** [comment]
OK, we can now close this issue.
